name: hola

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  ejecutar-python:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          python-location: '/usr/bin/python3.9'
      - name: Ejecutar script Python
        run: python hola.py Oscar
