name: hola

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  ejecutar-python:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Ejecutar script Python
        run: python3.9 hola.py Oscar
