name: scrapping

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Instalar requests
        run: pip install requests    

      - name: Instalar bs4
        run: pip install bs4  
        
      - name: Ejecutar script Python
        run: python scrapping.py

      - name: Commit y push del archivo generado
        run: |
          git config --global user.name "homerj31"
          git config --global user.email "obecerril.basalo@gmail.com"
          git add pagina.html
          git commit -m "Añadir archivo HTML generado por scraping" || echo "Sin cambios para commitear"
          git push        
