name: scrapping

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
  ejecutar-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Instalar requests
        run: pip install requests    

      - name: Instalar bs4
        run: pip install bs4  
        
      - name: Ejecutar script Python
        run: python scrapping.py

      - name: Guardar HTML como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: pagina
          path: pagina.html     

      - name: Guardar enalces como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: enlaces
          path: enlaces.txt           